#include "TOTVS.CH"
#include "Protheus.ch"

User Function TST00003()

	Private oDlg
	Private cTituloJanela := "Projeto 1 - Cadastro de Protheuzeiro"
	Private aFolder := {"Dados Pessoais","Endereço","Outros"}
	Private oFolder

	Private oGroupSexo //Agrupador de elementos que receberá os RadioButtons de Sexo

	Private aSexo           := {"Masculino","Feminino"}
	Private nSexo           := 2
	Private oRadioSexo
	Private oComboImovel
	Private oComboEstado
	Private aEstados        := {"AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RO", "RS", "RR", "SC", "SE", "SP", "TO"}
	Private cEstados        := aEstados[26]

	Private aImoveis       := {"Casa","Apartamento","Outro"}
	Private cImovel        := aImoveis[2]

	Private oSayEstCivil
	Private aEstCivil := {"Solteiro","Namorando","Casado","Protheuzando","Codificando","Vagando na net","Só no Insta","O pai tá on","Casado com Protheus","Namorando ADVPL"}
	Private cEstCivil  := aEstCivil[4]
	Private oComboEstCivil

	Private oGroupPet

	Private aPet := {"Sim","Não"}
	Private nPet  := 2
	Private oRadioPet

	Private oGroupLinguagens

	Private oCheckAdvpl
	Private oCheckSQL
	Private oCheckCSHARP
	Private oCheckPython

	Private lCheckAdvpl   := .F.
	Private lCheckSQL     := .F.
	Private lCheckCSHARP  := .F.
	Private lCheckPython  := .F.

	Private oButtonMarkAll
	Private oButtonUnMarkAll

	Private oSayObservacao
	Private cObservacao
	Private oTMultigetObservacao

	Private oButtonAba03


	Private aDados := {Space(30),Space(30),Space(30),Space(30),Space(30),Space(30)}
	Private oSay1,oSay2,oSay3,oSay4,oSay5,oSay6,oSay7,oSay8,oSay9,oSay10,oSay11,oSay12,oSayCod
	Private oGet1,oGet2,oGet3,oGet4,oGet5,oGet6,oGet7,oGet8,oGet9,oGet10,oGetCod

	cGet1   := Space(30)
	cGet2   := Space(30)
	dGet3   := Date()
	cGet4   := Space(4)
	cGet5   := Space(13)
	cGet6   := Space(14)
	cGet7   := Space(40)
	cGet8   := Space(30)
	cGet9   := Space(9)
	cGet10  := Space(30)
	cGetCod := Space(6)


	oDlg := TDialog():New(0,0,500,1280,cTituloJanela,,,,,CLR_BLACK,CLR_WHITE,,,.T.)
	oFolder     := TFolder():New(0,0,aFolder,aFolder,oDlg,,,,.T.,,644,200)

	oSay1 := TSay():New(001,005,{||'Nome'},oFolder:aDialogs[1],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
	oGet1 := TGet():New(010,005,{|u| IIF(Pcount()>0,cGet1 :=  u,cGet1)},oFolder:aDialogs[1],096,009,"",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet1,,,, )

	oSay2 := TSay():New(001,110,{||'Nome Reduzido'},oFolder:aDialogs[1],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
	oGet2 := TGet():New(010,110,{|u| IIF(Pcount()>0,cGet2 :=  u,cGet2)},oFolder:aDialogs[1],60,009,"",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet2,,,, )

	oSay3 := TSay():New(001,180,{||'Data de Nascimento'},oFolder:aDialogs[1],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
	oGet3 := TGet():New(010,180,{|u| IIF(PCount()>0,dGet3 :=  u,dGet3)},oFolder:aDialogs[1],60,009,,,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,/**/,,,,.T. )

	oSay4 := TSay():New(001,250,{||'DDD Cel.'},oFolder:aDialogs[1],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
	oGet4 := TGet():New(010,250,{|u| IIF(Pcount()>0,cGet4 :=  u,cGet4)},oFolder:aDialogs[1],20,009,"@E (99)",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet4,,,, )

	oSay5 := TSay():New(001,280,{||'Celular'},oFolder:aDialogs[1],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
	oGet5 := TGet():New(010,280,{|u| IIF(Pcount()>0,cGet5 :=  u,cGet5)},oFolder:aDialogs[1],40,009,"@E 99999-9999",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet5,,,, )

	oSay6 := TSay():New(025,005,{||'CPF'},oFolder:aDialogs[1],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
	oGet6 := TGet():New(035,005,{|u| IIF(Pcount()>0,cGet6 :=  u,cGet6)},oFolder:aDialogs[1],096,009,"@E 999.999.999-99",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet6,,,, )

	oSayCod := TSay():New(025,110,{||'Código'},oFolder:aDialogs[1],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
	oGetCod := TGet():New(035,110,{|u| IIF(Pcount()>0,cGetCod :=  u,cGetCod)},oFolder:aDialogs[1],040,009,"",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGetCod,,,, )
	oGetCod:cF3 := "ZZA"
	
	oGroupSexo      := tGroup():New(01,330,50,430,"Sexo",oFolder:aDialogs[1],,,.T.) //Preste atenção no dimensionamento/tamanho do elemento, este é diferente dos outros
	oRadioSexo  := tRadMenu():New(10,340,aSexo,{|u| iif(PCount()>0,nSexo :=u,nSexo )},oFolder:aDialogs[1],,,,,,,,60,20,,,,.T.)

	oButtonAba01      := TButton():New(160, 010, "VALIDAR DADOS PESSOAIS",    oFolder:aDialogs[1],{|| ShowDadosPessoais()}, 100,15,,,.F.,.T.,.F.,,.F.,,,.F. )

//=============================================================================================================================================================================================================================

	oSay7    := TSay():New(01,05,{||'Endereço'},oFolder:aDialogs[2],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
	oGet7    := TGet():New( 10,05,{|u| IIF(Pcount()>0,cGet7:=u,cGet7)},oFolder:aDialogs[2],096,009,"",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet7,,,, )

	oSay8      := TSay():New(01,110,{||'Bairro'},oFolder:aDialogs[2],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
	oGet8      := TGet():New( 10,110,{|u| IIF(Pcount()>0,cGet8:=u,cGet8)},oFolder:aDialogs[2],60,009,"",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet8,,,, )

	oSay9      := TSay():New(01,180,{||'Tipo de Imóvel'},oFolder:aDialogs[2],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
	oComboImovel    := tComboBox():New(010,180,{|u|if(PCount()>0,cImovel:=u,cImovel)},aImoveis,60,20,oFolder:aDialogs[2],,,,,,.T.,,,,,,,,,'cImovel')

	oSay10         := TSay():New(01,250,{||'CEP'},oFolder:aDialogs[2],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
	oGet9         := TGet():New( 10,250,{|u| IIF(Pcount()>0,cGet9:=u,cGet9)},oFolder:aDialogs[2],30,009,"@E 99999-999",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet9,,,, )

	oSay11      := TSay():New(25,05,{||'Estado'},oFolder:aDialogs[2],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
	oComboEstado    := tComboBox():New(35,05,{|u|if(PCount()>0,cEstados:=u,cEstados)},aEstados,40,20,oFolder:aDialogs[2],,,,,,.T.,,,,,,,,,'cEstado')

	oSay12      := TSay():New(25,50,{||'Cidade'},oFolder:aDialogs[2],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
	oGet10      := TGet():New( 35,50,{|u| IIF(Pcount()>0,cGet10:=u,cGet10)},oFolder:aDialogs[2],096,009,"",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGet10,,,, )

	oButtonAba02    := TButton():New(160, 010, "VALIDAR ENDEREÇO",    oFolder:aDialogs[2],{|| ShowEndereco()}, 100,15,,,.F.,.T.,.F.,,.F.,,,.F. )

//=============================================================================================================================================================================================================================

	oSayEstCivil       := TSay():New(01,05,{||'Estado Civil'},oFolder:aDialogs[3],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
	oComboEstCivil     := tComboBox():New(10,05,{|u|if(PCount()>0,cEstCivil:=u,cEstCivil)},aEstCivil,65,20,oFolder:aDialogs[3],,/**/,,,,.T.,,,,,,,,,'cCombo')

	oGroupPet          := tGroup():New(01,80,40,140,"Possui Pet?",oFolder:aDialogs[3],,,.T.)
	oRadioPet          := tRadMenu():New(10,85,aPet,{|u| iif(PCount()>0,nPet :=u,nPet )},oFolder:aDialogs[3],,,,,,,,30,20,,,,.T.)

	oGroupLinguagens   := tGroup():New(01,150,55,250,"Linguagens que domina:",oFolder:aDialogs[3],,,.T.)

	oCheckADVPL         := TCheckBox():New(10,160,'ADVPL',{|| lCheckADVPL},oFolder:aDialogs[3],100,210,,{|| lCheckADVPL := !lCheckADVPL},,,,,,.T.,,,)

	oCheckSQL           := TCheckBox():New(20,160,'SQL',,oFolder:aDialogs[3],100,210,,,,,,,,.T.,,,)
	oCheckSQL:bSetGet   := {|| lCheckSQL}
	oCheckSQL:bLClicked := {|| lCheckSQL := !lCheckSQL}

	oCheckCSHARP            := TCheckBox():New(30,160,'CSharp',,oFolder:aDialogs[3],100,210,,,,,,,,.T.,,,)
	oCheckCSHARP:bSetGet    := {|| lCheckCSHARP}
	oCheckCSHARP:bLClicked  := {|| lCheckCSHARP := !lCheckCSHARP}

	oCheckPython            := TCheckBox():New(40,160,'Python',,oFolder:aDialogs[3],100,210,,,,,,,,.T.,,,)
	oCheckPython:bSetGet    := {|| lCheckPython}
	oCheckPython:bLClicked  := {|| lCheckPython := !lCheckPython}

	oButtonMarkAll   := TButton():New(15, 200, "Todas", oFolder:aDialogs[3],;
		{|| lCheckADVPL := .T.,lCheckSQL := .T., lCheckCSHARP := .T., lCheckPython := .T.}, 40,10,,,.F.,.T.,.F.,,.F.,,,.F. )

	oButtonUnMarkAll   := TButton():New(30, 200, "Nenhuma", oFolder:aDialogs[3],;
		{|| lCheckADVPL := .F.,lCheckSQL := .F., lCheckCSHARP := .F., lCheckPython := .F.}, 40,10,,,.F.,.T.,.F.,,.F.,,,.F. )

	oSayObservacao       := TSay():New(01,270,{||'Observacao'},oFolder:aDialogs[3],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
	cObservacao          := "Digite aqui as características de Protheuzeiro que te definem"
	oTMultigetObservacao := TMultiget():New(10,270, {|u|if(pCount()>0,cObservacao := u, cObservacao) }, oFolder:aDialogs[3], 200, 100, , , , , , .T. )

	oButtonAba03      := TButton():New(160, 010, "VALIDAR OUTROS",    oFolder:aDialogs[3],{|| ShowOutros()}, 100,15,,,.F.,.T.,.F.,,.F.,,,.F. )

//=============================================================================================================================================================================================================================

	oButtonIncluir      := TButton():New(220, 10, "Incluir",    oDlg, {|| xIncluir() }, 40,15,,,.F.,.T.,.F.,,.F.,,,.F. )
	oButtonAlterar      := TButton():New(220, 70, "Alterar",    oDlg,{|| xAlterar()}, 40,15,,,.F.,.T.,.F.,,.F.,,,.F. )
	oButtonConsultar    := TButton():New(220, 130, "Consultar", oDlg,{|| xConsultar()}, 40,15,,,.F.,.T.,.F.,,.F.,,,.F. )
	oButtonExcluir      := TButton():New(220, 190, "Excluir",   oDlg,{|| xIExcluir()}, 40,15,,,.F.,.T.,.F.,,.F.,,,.F. )

	oDlg:Activate(,,,.T.)
Return

Static Function ShowDadosPessoais()

	MsgInfo("Nome:............."+cGet1+Chr(13)+Chr(10)+;
		"Nome Reduzido:...."+cGet2+Chr(13)+Chr(10)+;
		"Nascimento:......."+DToc(dGet3)+Chr(13)+Chr(10)+;
		"Telefone:........."+cGet4+"-"+cGet5+Chr(13)+Chr(10)+;
		"Sexo:............."+aSexo[nSexo]+Chr(13)+Chr(10)+;
		"CPF:.............."+cGet6,"ABA DADOS PESSOAIS")

return

Static Function ShowEndereco()

	MsgInfo("Endereço:....."+cGet9+Chr(13)+Chr(10)+;
		"Bairro:......."+cGet10+Chr(13)+Chr(10)+;
		"Imovel:......."+cImovel+Chr(13)+Chr(10)+;
		"CEP:.........."+cGet9+Chr(13)+Chr(10)+;
		"Estado:......."+cEstados+Chr(13)+Chr(10)+;
		"Cidade:......."+cGet10,"ABA ENDERECO")

return
Static Function ShowOutros()

	MsgInfo("Estado Civil:...."+cEstCivil+Chr(13)+Chr(10)+;
		"Possui Pet:......"+aPet[nPet]+Chr(13)+Chr(10)+;
		"ADVPL?:.........."+IIF(lCheckADVPL = .T.,"Sim","Não")+Chr(13)+Chr(10)+;
		"SQL?:............"+IIF(lCheckSQL,"Sim","Não")+Chr(13)+Chr(10)+;
		"CSHARP?:........."+IIF(lCheckCSHARP,"Sim","Não")+Chr(13)+Chr(10)+;
		"PYTHON?:........."+IIF(lCheckPython,"Sim","Não")+Chr(13)+Chr(10)+;
		"Observacao:......"+cObservacao,"ABA OUTROS")
return

Static Function xIncluir()
    
    DBSelectArea("ZZA")
    IF Reclock("ZZA",.T.)
    
    	ZZA-> ZZA_FILIAL    := FWXfilial("ZZA")
    	ZZA-> ZZA_COD       := GetSxeNum("ZZA","ZZA_COD")
    	ZZA-> ZZA_NOME      := cGet1
    	ZZA-> ZZA_NREDUZ    := cGet2
    	ZZA-> ZZA_DATNAS    := dGet3
    	ZZA-> ZZA_DDD       := StrTran(StrTran(cGet4,"(",""),")","")
    	ZZA-> ZZA_CEL       := StrTran(cGet5,"-","")
    	ZZA-> ZZA_SEXO      := cValToChar(nSexo)
    	ZZA-> ZZA_CPF       := StrTran(StrTran(cGet6,".",""),"-","")
	
    	ZZA-> ZZA_END       := cGet9
    	ZZA-> ZZA_BAIRRO    := cGet10
    	ZZA-> ZZA_TIPIMO    := cImovel
    	ZZA-> ZZA_CEP       := StrTran(cGet9,"-","")
    	ZZA-> ZZA_ESTADO    := cEstados
    	ZZA-> ZZA_CIDADE    := cGet10
	
    	ZZA-> ZZA_ESTCIV    := cEstCivil
    	ZZA-> ZZA_TEMPET    := cValToChar(nPet)
    	ZZA-> ZZA_LADVPL    := IIF(lCheckADVPL,	"Sim","Não")
    	ZZA-> ZZA_LSQL      := IIF(lCheckSQL,	"Sim","Não")
    	ZZA-> ZZA_LC        := IIF(lCheckCSHARP,"Sim","Não")
    	ZZA-> ZZA_PYTHON    := IIF(lCheckPython,"Sim","Não")
    	ZZA-> ZZA_OBS       := cObservacao
    
    	MsUnlock()
		MsgInfo("Registro Incluido com sucesso")
	else
		MsgAlert("Não foi possível incluir o registro na tabela")
	EndIf
    DBCloseArea()
return

Static Function xConsultar()
    Local lOk := .T.

	If Empty(cGetCod)
		lOk := .F.
	EndIf

	DBSelectArea("ZZA")
	If lOk .AND. dbSeek(FWXfilial("ZZA") + cGetCod)     // Filial: 01 / Código: 000001 / Loja: 02
    	cGetCod 	 := ZZA-> ZZA_COD
    	cGet1 		 := ZZA-> ZZA_NOME
        cGet2 		 := ZZA-> ZZA_NREDUZ
    	dGet3 		 := ZZA-> ZZA_DATNAS
		cGet4 		 := ZZA-> ZZA_DDD
		cGet5 		 := ZZA-> ZZA_CEL
		nSexo 		 := Val(ZZA->ZZA_SEXO)
		cGet6 		 := ZZA-> ZZA_CPF
		cGet9 		 := ZZA-> ZZA_END
		cGet10 		 := ZZA-> ZZA_BAIRRO
		cImovel 	 := ZZA-> ZZA_TIPIMO
		cGet9 		 := ZZA-> ZZA_CEP
		cEstados 	 := ZZA-> ZZA_ESTADO
		cGet10 		 := ZZA-> ZZA_CIDADE
		cEstCivil 	 := ZZA-> ZZA_ESTCIV
		nPet 		 := Val(ZZA-> ZZA_TEMPET)
		lCheckADVPL  := IIF(ZZA-> ZZA_LADVPL == "S",.T.,.F.)
		lCheckSQL	 := IIF(ZZA-> ZZA_LSQL 	 == "S",.T.,.F.)
		lCheckCSHARP := IIF(ZZA-> ZZA_LC 	 == "S",.T.,.F.)
		lCheckPython := IIF(ZZA-> ZZA_PYTHON == "S",.T.,.F.)
		cObservacao  := ZZA-> ZZA_OBS

        MsgInfo("Cliente localizado", "Consulta por cliente")
	Else
  	    MsgInfo("Cliente não encontrado", "Consulta por cliente")
	EndIf
    DBCloseArea()
	oDlg:Refresh()
return
